# Github Personal Access Token (https://github.com/settings/tokens) with rights:
# - "repo - public_repo"
# - "admin:org - read:org"
token:

# HAWK Catcher TOKEN
hawk_token:

# Columns Nodes id
# To get these values use any app for sending requests (Insomnia for example) and send the following request
# Use your data for the YOUR_GITHUB_PERSONAL_ACCESS_TOKEN, org name and number of project (11 in this example) from it's link
# If everything is correct you will get a list of project's columns with theis node id's which you need for the script.
#
# Endpoint: https://api.github.com/graphql
# Request Type: POST
# Headers:
#     Authorization: bearer YOUR_GITHUB_PERSONAL_ACCESS_TOKEN
#     Content-Type: application/json
#     User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
# Body Type: GraphQL
# Body:
#     query {
#       organization(login: "codex-team") {
#         project(number: 11) {
#           id,
#           name,
#           columns(first: 10) {
#             edges {
#               node {
#                 id,
#                 name
#               }
#             }
#           }
#         }
#       }
#     }
column_node_id_to_do:
column_node_id_pr:

# @codex_bot notify URL
# Open https://t.me/codex_bot
# And run /notify command
notifier_url:

# Define jobs
# Example: 0 9,18 * * 1-5
# At minute 0 past hour 9 and 18 on every day-of-week from Monday through Friday.
to_do_time: 0 9,18 * * 1-5
pr_time: 0 9,18 * * 1-5
meeting_time: 0 9,18 * * 1-5

# List of people (Telegram only) to tag in the «Meeting Message» message
meeting_mention:
  - nvc_8996
  # - n0str

# List of people to tag in the «Pull Requests» message
# Separated Github and Telegram usernames if they differ.
mention:
  # - n0str
  - tg: nvc_8996
    gh: nvc8996
